package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	private int idarticle;
	private Lot lot;
	private Promotion promotion;
	private String qrcode;
	private Byte prixachat;
	private Byte prixvente;
	private Byte tva;
	private Byte quantiteinitial;
	private Boolean statut;
	private Byte quantitedisponible;
	private Date datecreation;
	private Date dateexpiration;
	private Byte seiulalert;
	private Set varietes = new HashSet(0);
	private Set retourproduits = new HashSet(0);
	private Set detailventes = new HashSet(0);
	private Set livraisons = new HashSet(0);
	private Set images = new HashSet(0);

	public Article() {
	}

	public Article(int idarticle, Lot lot) {
		this.idarticle = idarticle;
		this.lot = lot;
	}

	public Article(int idarticle, Lot lot, Promotion promotion, String qrcode, Byte prixachat, Byte prixvente, Byte tva,
			Byte quantiteinitial, Boolean statut, Byte quantitedisponible, Date datecreation, Date dateexpiration,
			Byte seiulalert, Set varietes, Set retourproduits, Set detailventes, Set livraisons, Set images) {
		this.idarticle = idarticle;
		this.lot = lot;
		this.promotion = promotion;
		this.qrcode = qrcode;
		this.prixachat = prixachat;
		this.prixvente = prixvente;
		this.tva = tva;
		this.quantiteinitial = quantiteinitial;
		this.statut = statut;
		this.quantitedisponible = quantitedisponible;
		this.datecreation = datecreation;
		this.dateexpiration = dateexpiration;
		this.seiulalert = seiulalert;
		this.varietes = varietes;
		this.retourproduits = retourproduits;
		this.detailventes = detailventes;
		this.livraisons = livraisons;
		this.images = images;
	}

	public int getIdarticle() {
		return this.idarticle;
	}

	public void setIdarticle(int idarticle) {
		this.idarticle = idarticle;
	}

	public Lot getLot() {
		return this.lot;
	}

	public void setLot(Lot lot) {
		this.lot = lot;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public String getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	public Byte getPrixachat() {
		return this.prixachat;
	}

	public void setPrixachat(Byte prixachat) {
		this.prixachat = prixachat;
	}

	public Byte getPrixvente() {
		return this.prixvente;
	}

	public void setPrixvente(Byte prixvente) {
		this.prixvente = prixvente;
	}

	public Byte getTva() {
		return this.tva;
	}

	public void setTva(Byte tva) {
		this.tva = tva;
	}

	public Byte getQuantiteinitial() {
		return this.quantiteinitial;
	}

	public void setQuantiteinitial(Byte quantiteinitial) {
		this.quantiteinitial = quantiteinitial;
	}

	public Boolean getStatut() {
		return this.statut;
	}

	public void setStatut(Boolean statut) {
		this.statut = statut;
	}

	public Byte getQuantitedisponible() {
		return this.quantitedisponible;
	}

	public void setQuantitedisponible(Byte quantitedisponible) {
		this.quantitedisponible = quantitedisponible;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Date getDateexpiration() {
		return this.dateexpiration;
	}

	public void setDateexpiration(Date dateexpiration) {
		this.dateexpiration = dateexpiration;
	}

	public Byte getSeiulalert() {
		return this.seiulalert;
	}

	public void setSeiulalert(Byte seiulalert) {
		this.seiulalert = seiulalert;
	}

	public Set getVarietes() {
		return this.varietes;
	}

	public void setVarietes(Set varietes) {
		this.varietes = varietes;
	}

	public Set getRetourproduits() {
		return this.retourproduits;
	}

	public void setRetourproduits(Set retourproduits) {
		this.retourproduits = retourproduits;
	}

	public Set getDetailventes() {
		return this.detailventes;
	}

	public void setDetailventes(Set detailventes) {
		this.detailventes = detailventes;
	}

	public Set getLivraisons() {
		return this.livraisons;
	}

	public void setLivraisons(Set livraisons) {
		this.livraisons = livraisons;
	}

	public Set getImages() {
		return this.images;
	}

	public void setImages(Set images) {
		this.images = images;
	}

}
