package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Assoreporttransat generated by hbm2java
 */
public class Assoreporttransat implements java.io.Serializable {

	private AssoreporttransatId id;
	private Rapportfinancier rapportfinancier;
	private Transaction transaction;
	private Date date;

	public Assoreporttransat() {
	}

	public Assoreporttransat(AssoreporttransatId id, Rapportfinancier rapportfinancier, Transaction transaction) {
		this.id = id;
		this.rapportfinancier = rapportfinancier;
		this.transaction = transaction;
	}

	public Assoreporttransat(AssoreporttransatId id, Rapportfinancier rapportfinancier, Transaction transaction,
			Date date) {
		this.id = id;
		this.rapportfinancier = rapportfinancier;
		this.transaction = transaction;
		this.date = date;
	}

	public AssoreporttransatId getId() {
		return this.id;
	}

	public void setId(AssoreporttransatId id) {
		this.id = id;
	}

	public Rapportfinancier getRapportfinancier() {
		return this.rapportfinancier;
	}

	public void setRapportfinancier(Rapportfinancier rapportfinancier) {
		this.rapportfinancier = rapportfinancier;
	}

	public Transaction getTransaction() {
		return this.transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
