package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Assocomptecaisse generated by hbm2java
 */
public class Assocomptecaisse implements java.io.Serializable {

	private AssocomptecaisseId id;
	private Caisse caisse;
	private Compte compte;
	private String heurdebut;
	private String heurfin;
	private Byte montantinitial;
	private Byte montantfinal;
	private Date date;
	private Set ventes = new HashSet(0);

	public Assocomptecaisse() {
	}

	public Assocomptecaisse(AssocomptecaisseId id, Caisse caisse, Compte compte) {
		this.id = id;
		this.caisse = caisse;
		this.compte = compte;
	}

	public Assocomptecaisse(AssocomptecaisseId id, Caisse caisse, Compte compte, String heurdebut, String heurfin,
			Byte montantinitial, Byte montantfinal, Date date, Set ventes) {
		this.id = id;
		this.caisse = caisse;
		this.compte = compte;
		this.heurdebut = heurdebut;
		this.heurfin = heurfin;
		this.montantinitial = montantinitial;
		this.montantfinal = montantfinal;
		this.date = date;
		this.ventes = ventes;
	}

	public AssocomptecaisseId getId() {
		return this.id;
	}

	public void setId(AssocomptecaisseId id) {
		this.id = id;
	}

	public Caisse getCaisse() {
		return this.caisse;
	}

	public void setCaisse(Caisse caisse) {
		this.caisse = caisse;
	}

	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	public String getHeurdebut() {
		return this.heurdebut;
	}

	public void setHeurdebut(String heurdebut) {
		this.heurdebut = heurdebut;
	}

	public String getHeurfin() {
		return this.heurfin;
	}

	public void setHeurfin(String heurfin) {
		this.heurfin = heurfin;
	}

	public Byte getMontantinitial() {
		return this.montantinitial;
	}

	public void setMontantinitial(Byte montantinitial) {
		this.montantinitial = montantinitial;
	}

	public Byte getMontantfinal() {
		return this.montantfinal;
	}

	public void setMontantfinal(Byte montantfinal) {
		this.montantfinal = montantfinal;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set getVentes() {
		return this.ventes;
	}

	public void setVentes(Set ventes) {
		this.ventes = ventes;
	}

}
