package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Caisse generated by hbm2java
 */
public class Caisse implements java.io.Serializable {

	private int idcaisse;
	private Date dateouverture;
	private Date datefermeture;
	private String statut;
	private Set assocomptecaisses = new HashSet(0);

	public Caisse() {
	}

	public Caisse(int idcaisse) {
		this.idcaisse = idcaisse;
	}

	public Caisse(int idcaisse, Date dateouverture, Date datefermeture, String statut, Set assocomptecaisses) {
		this.idcaisse = idcaisse;
		this.dateouverture = dateouverture;
		this.datefermeture = datefermeture;
		this.statut = statut;
		this.assocomptecaisses = assocomptecaisses;
	}

	public int getIdcaisse() {
		return this.idcaisse;
	}

	public void setIdcaisse(int idcaisse) {
		this.idcaisse = idcaisse;
	}

	public Date getDateouverture() {
		return this.dateouverture;
	}

	public void setDateouverture(Date dateouverture) {
		this.dateouverture = dateouverture;
	}

	public Date getDatefermeture() {
		return this.datefermeture;
	}

	public void setDatefermeture(Date datefermeture) {
		this.datefermeture = datefermeture;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public Set getAssocomptecaisses() {
		return this.assocomptecaisses;
	}

	public void setAssocomptecaisses(Set assocomptecaisses) {
		this.assocomptecaisses = assocomptecaisses;
	}

}
