package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Catalogue generated by hbm2java
 */
public class Catalogue implements java.io.Serializable {

	private int idcatalogue;
	private String reference;
	private String label;
	private String description;
	private Date datecreation;
	private Boolean etat;
	private Set familles = new HashSet(0);

	public Catalogue() {
	}

	public Catalogue(int idcatalogue) {
		this.idcatalogue = idcatalogue;
	}

	public Catalogue(int idcatalogue, String reference, String label, String description, Date datecreation,
			Boolean etat, Set familles) {
		this.idcatalogue = idcatalogue;
		this.reference = reference;
		this.label = label;
		this.description = description;
		this.datecreation = datecreation;
		this.etat = etat;
		this.familles = familles;
	}

	public int getIdcatalogue() {
		return this.idcatalogue;
	}

	public void setIdcatalogue(int idcatalogue) {
		this.idcatalogue = idcatalogue;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Boolean getEtat() {
		return this.etat;
	}

	public void setEtat(Boolean etat) {
		this.etat = etat;
	}

	public Set getFamilles() {
		return this.familles;
	}

	public void setFamilles(Set familles) {
		this.familles = familles;
	}

}
