package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categorietransaction generated by hbm2java
 */
public class Categorietransaction implements java.io.Serializable {

	private int idcattrans;
	private String nom;
	private String type;
	private Set transactions = new HashSet(0);

	public Categorietransaction() {
	}

	public Categorietransaction(int idcattrans) {
		this.idcattrans = idcattrans;
	}

	public Categorietransaction(int idcattrans, String nom, String type, Set transactions) {
		this.idcattrans = idcattrans;
		this.nom = nom;
		this.type = type;
		this.transactions = transactions;
	}

	public int getIdcattrans() {
		return this.idcattrans;
	}

	public void setIdcattrans(int idcattrans) {
		this.idcattrans = idcattrans;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

}
