package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private ClientId id;
	private Personne personne;
	private String matricule;
	private Set ventes = new HashSet(0);

	public Client() {
	}

	public Client(ClientId id, Personne personne) {
		this.id = id;
		this.personne = personne;
	}

	public Client(ClientId id, Personne personne, String matricule, Set ventes) {
		this.id = id;
		this.personne = personne;
		this.matricule = matricule;
		this.ventes = ventes;
	}

	public ClientId getId() {
		return this.id;
	}

	public void setId(ClientId id) {
		this.id = id;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	public Set getVentes() {
		return this.ventes;
	}

	public void setVentes(Set ventes) {
		this.ventes = ventes;
	}

}
