package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compte generated by hbm2java
 */
public class Compte implements java.io.Serializable {

	private int idconnexion;
	private Personne personne;
	private String identifiant;
	private String motdepasse;
	private Date datecreation;
	private String etat;
	private Set assocomptecaisses = new HashSet(0);
	private Set historiques = new HashSet(0);
	private Set patternes = new HashSet(0);
	private Set rapportfinanciers = new HashSet(0);
	private Set transactions = new HashSet(0);
	private Set boutiques = new HashSet(0);
	private Set roles = new HashSet(0);

	public Compte() {
	}

	public Compte(int idconnexion, Personne personne) {
		this.idconnexion = idconnexion;
		this.personne = personne;
	}

	public Compte(int idconnexion, Personne personne, String identifiant, String motdepasse, Date datecreation,
			String etat, Set assocomptecaisses, Set historiques, Set patternes, Set rapportfinanciers, Set transactions,
			Set boutiques, Set roles) {
		this.idconnexion = idconnexion;
		this.personne = personne;
		this.identifiant = identifiant;
		this.motdepasse = motdepasse;
		this.datecreation = datecreation;
		this.etat = etat;
		this.assocomptecaisses = assocomptecaisses;
		this.historiques = historiques;
		this.patternes = patternes;
		this.rapportfinanciers = rapportfinanciers;
		this.transactions = transactions;
		this.boutiques = boutiques;
		this.roles = roles;
	}

	public int getIdconnexion() {
		return this.idconnexion;
	}

	public void setIdconnexion(int idconnexion) {
		this.idconnexion = idconnexion;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	public String getMotdepasse() {
		return this.motdepasse;
	}

	public void setMotdepasse(String motdepasse) {
		this.motdepasse = motdepasse;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Set getAssocomptecaisses() {
		return this.assocomptecaisses;
	}

	public void setAssocomptecaisses(Set assocomptecaisses) {
		this.assocomptecaisses = assocomptecaisses;
	}

	public Set getHistoriques() {
		return this.historiques;
	}

	public void setHistoriques(Set historiques) {
		this.historiques = historiques;
	}

	public Set getPatternes() {
		return this.patternes;
	}

	public void setPatternes(Set patternes) {
		this.patternes = patternes;
	}

	public Set getRapportfinanciers() {
		return this.rapportfinanciers;
	}

	public void setRapportfinanciers(Set rapportfinanciers) {
		this.rapportfinanciers = rapportfinanciers;
	}

	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

	public Set getBoutiques() {
		return this.boutiques;
	}

	public void setBoutiques(Set boutiques) {
		this.boutiques = boutiques;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

}
