package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Conge generated by hbm2java
 */
public class Conge implements java.io.Serializable {

	private int idconge;
	private Employer employer;
	private String typeconge;
	private Date datedebut;
	private Date datefin;
	private String statutconge;

	public Conge() {
	}

	public Conge(int idconge, Employer employer) {
		this.idconge = idconge;
		this.employer = employer;
	}

	public Conge(int idconge, Employer employer, String typeconge, Date datedebut, Date datefin, String statutconge) {
		this.idconge = idconge;
		this.employer = employer;
		this.typeconge = typeconge;
		this.datedebut = datedebut;
		this.datefin = datefin;
		this.statutconge = statutconge;
	}

	public int getIdconge() {
		return this.idconge;
	}

	public void setIdconge(int idconge) {
		this.idconge = idconge;
	}

	public Employer getEmployer() {
		return this.employer;
	}

	public void setEmployer(Employer employer) {
		this.employer = employer;
	}

	public String getTypeconge() {
		return this.typeconge;
	}

	public void setTypeconge(String typeconge) {
		this.typeconge = typeconge;
	}

	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}

	public String getStatutconge() {
		return this.statutconge;
	}

	public void setStatutconge(String statutconge) {
		this.statutconge = statutconge;
	}

}
