package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Contrattravail generated by hbm2java
 */
public class Contrattravail implements java.io.Serializable {

	private int idcontrat;
	private Employer employer;
	private Payementsalaire payementsalaire;
	private Salaire salaire;
	private Typecontrat typecontrat;
	private Date datedebut;
	private Date datefin;
	private String statutcontrat;

	public Contrattravail() {
	}

	public Contrattravail(int idcontrat, Employer employer, Payementsalaire payementsalaire, Salaire salaire,
			Typecontrat typecontrat) {
		this.idcontrat = idcontrat;
		this.employer = employer;
		this.payementsalaire = payementsalaire;
		this.salaire = salaire;
		this.typecontrat = typecontrat;
	}

	public Contrattravail(int idcontrat, Employer employer, Payementsalaire payementsalaire, Salaire salaire,
			Typecontrat typecontrat, Date datedebut, Date datefin, String statutcontrat) {
		this.idcontrat = idcontrat;
		this.employer = employer;
		this.payementsalaire = payementsalaire;
		this.salaire = salaire;
		this.typecontrat = typecontrat;
		this.datedebut = datedebut;
		this.datefin = datefin;
		this.statutcontrat = statutcontrat;
	}

	public int getIdcontrat() {
		return this.idcontrat;
	}

	public void setIdcontrat(int idcontrat) {
		this.idcontrat = idcontrat;
	}

	public Employer getEmployer() {
		return this.employer;
	}

	public void setEmployer(Employer employer) {
		this.employer = employer;
	}

	public Payementsalaire getPayementsalaire() {
		return this.payementsalaire;
	}

	public void setPayementsalaire(Payementsalaire payementsalaire) {
		this.payementsalaire = payementsalaire;
	}

	public Salaire getSalaire() {
		return this.salaire;
	}

	public void setSalaire(Salaire salaire) {
		this.salaire = salaire;
	}

	public Typecontrat getTypecontrat() {
		return this.typecontrat;
	}

	public void setTypecontrat(Typecontrat typecontrat) {
		this.typecontrat = typecontrat;
	}

	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}

	public String getStatutcontrat() {
		return this.statutcontrat;
	}

	public void setStatutcontrat(String statutcontrat) {
		this.statutcontrat = statutcontrat;
	}

}
