package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

/**
 * Detailvente generated by hbm2java
 */
public class Detailvente implements java.io.Serializable {

	private DetailventeId id;
	private Article article;
	private Vente vente;
	private Byte quantite;
	private Byte prixunitaire;
	private Byte prixtotal;

	public Detailvente() {
	}

	public Detailvente(DetailventeId id, Article article, Vente vente) {
		this.id = id;
		this.article = article;
		this.vente = vente;
	}

	public Detailvente(DetailventeId id, Article article, Vente vente, Byte quantite, Byte prixunitaire,
			Byte prixtotal) {
		this.id = id;
		this.article = article;
		this.vente = vente;
		this.quantite = quantite;
		this.prixunitaire = prixunitaire;
		this.prixtotal = prixtotal;
	}

	public DetailventeId getId() {
		return this.id;
	}

	public void setId(DetailventeId id) {
		this.id = id;
	}

	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	public Vente getVente() {
		return this.vente;
	}

	public void setVente(Vente vente) {
		this.vente = vente;
	}

	public Byte getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Byte quantite) {
		this.quantite = quantite;
	}

	public Byte getPrixunitaire() {
		return this.prixunitaire;
	}

	public void setPrixunitaire(Byte prixunitaire) {
		this.prixunitaire = prixunitaire;
	}

	public Byte getPrixtotal() {
		return this.prixtotal;
	}

	public void setPrixtotal(Byte prixtotal) {
		this.prixtotal = prixtotal;
	}

}
