package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

/**
 * DetailventeId generated by hbm2java
 */
public class DetailventeId implements java.io.Serializable {

	private int idvente;
	private int idarticle;

	public DetailventeId() {
	}

	public DetailventeId(int idvente, int idarticle) {
		this.idvente = idvente;
		this.idarticle = idarticle;
	}

	public int getIdvente() {
		return this.idvente;
	}

	public void setIdvente(int idvente) {
		this.idvente = idvente;
	}

	public int getIdarticle() {
		return this.idarticle;
	}

	public void setIdarticle(int idarticle) {
		this.idarticle = idarticle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailventeId))
			return false;
		DetailventeId castOther = (DetailventeId) other;

		return (this.getIdvente() == castOther.getIdvente()) && (this.getIdarticle() == castOther.getIdarticle());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdvente();
		result = 37 * result + this.getIdarticle();
		return result;
	}

}
