package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.FetchType;
import javax.persistence.ManyToOne;

/**
 * Famille generated by hbm2java
 */
public class Famille implements java.io.Serializable {

	private int idfamille;
	
	@ManyToOne(fetch = FetchType.EAGER)
	private Catalogue catalogue;
	
	private String reference;
	private String label;
	private String description;
	private Date datecreation;
	private Boolean etat;
	private Set produits = new HashSet(0);

	public Famille() {
	}

	public Famille(int idfamille) {
		this.idfamille = idfamille;
	}

	public Famille(int idfamille, Catalogue catalogue, String reference, String label, String description,
			Date datecreation, Boolean etat, Set produits) {
		this.idfamille = idfamille;
		this.catalogue = catalogue;
		this.reference = reference;
		this.label = label;
		this.description = description;
		this.datecreation = datecreation;
		this.etat = etat;
		this.produits = produits;
	}

	public int getIdfamille() {
		return this.idfamille;
	}

	public void setIdfamille(int idfamille) {
		this.idfamille = idfamille;
	}

	public Catalogue getCatalogue() {
		return this.catalogue;
	}

	public void setCatalogue(Catalogue catalogue) {
		this.catalogue = catalogue;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Boolean getEtat() {
		return this.etat;
	}

	public void setEtat(Boolean etat) {
		this.etat = etat;
	}

	public Set getProduits() {
		return this.produits;
	}

	public void setProduits(Set produits) {
		this.produits = produits;
	}

}
