package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	private int idimage;
	private Article article;
	private String path;

	public Image() {
	}

	public Image(int idimage) {
		this.idimage = idimage;
	}

	public Image(int idimage, Article article, String path) {
		this.idimage = idimage;
		this.article = article;
		this.path = path;
	}

	public int getIdimage() {
		return this.idimage;
	}

	public void setIdimage(int idimage) {
		this.idimage = idimage;
	}

	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
