package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Lot generated by hbm2java
 */
public class Lot implements java.io.Serializable {

	private int idlot;
	private Boutique boutique;
	private Produit produit;
	private Stock stock;
	private Integer reference;
	private String libelle;
	private String decription;
	private Integer statut;
	private Integer datemodification;
	private Integer datecreation;
	private Set articles = new HashSet(0);

	public Lot() {
	}

	public Lot(int idlot, Produit produit, Stock stock) {
		this.idlot = idlot;
		this.produit = produit;
		this.stock = stock;
	}

	public Lot(int idlot, Boutique boutique, Produit produit, Stock stock, Integer reference, String libelle,
			String decription, Integer statut, Integer datemodification, Integer datecreation, Set articles) {
		this.idlot = idlot;
		this.boutique = boutique;
		this.produit = produit;
		this.stock = stock;
		this.reference = reference;
		this.libelle = libelle;
		this.decription = decription;
		this.statut = statut;
		this.datemodification = datemodification;
		this.datecreation = datecreation;
		this.articles = articles;
	}

	public int getIdlot() {
		return this.idlot;
	}

	public void setIdlot(int idlot) {
		this.idlot = idlot;
	}

	public Boutique getBoutique() {
		return this.boutique;
	}

	public void setBoutique(Boutique boutique) {
		this.boutique = boutique;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public Integer getReference() {
		return this.reference;
	}

	public void setReference(Integer reference) {
		this.reference = reference;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getDecription() {
		return this.decription;
	}

	public void setDecription(String decription) {
		this.decription = decription;
	}

	public Integer getStatut() {
		return this.statut;
	}

	public void setStatut(Integer statut) {
		this.statut = statut;
	}

	public Integer getDatemodification() {
		return this.datemodification;
	}

	public void setDatemodification(Integer datemodification) {
		this.datemodification = datemodification;
	}

	public Integer getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Integer datecreation) {
		this.datecreation = datecreation;
	}

	public Set getArticles() {
		return this.articles;
	}

	public void setArticles(Set articles) {
		this.articles = articles;
	}

}
