package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Permission generated by hbm2java
 */
public class Permission implements java.io.Serializable {

	private int idpermission;
	private String libelle;
	private String reference;
	private Boolean etat;
	private Date datecreation;
	private String description;
	private Set roles = new HashSet(0);

	public Permission() {
	}

	public Permission(int idpermission) {
		this.idpermission = idpermission;
	}

	public Permission(int idpermission, String libelle, String reference, Boolean etat, Date datecreation,
			String description, Set roles) {
		this.idpermission = idpermission;
		this.libelle = libelle;
		this.reference = reference;
		this.etat = etat;
		this.datecreation = datecreation;
		this.description = description;
		this.roles = roles;
	}

	public int getIdpermission() {
		return this.idpermission;
	}

	public void setIdpermission(int idpermission) {
		this.idpermission = idpermission;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Boolean getEtat() {
		return this.etat;
	}

	public void setEtat(Boolean etat) {
		this.etat = etat;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

}
