package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit implements java.io.Serializable {

	private int idproduit;
	private Famille famille;
	private String reference;
	private String designation;
	private String description;
	private Boolean etat;
	private Date datecreation;
	private Set detaiproduits = new HashSet(0);
	private Set assoproduitunites = new HashSet(0);
	private Set lots = new HashSet(0);

	public Produit() {
	}

	public Produit(int idproduit) {
		this.idproduit = idproduit;
	}

	public Produit(int idproduit, Famille famille, String reference, String designation, String description,
			Boolean etat, Date datecreation, Set detaiproduits, Set assoproduitunites, Set lots) {
		this.idproduit = idproduit;
		this.famille = famille;
		this.reference = reference;
		this.designation = designation;
		this.description = description;
		this.etat = etat;
		this.datecreation = datecreation;
		this.detaiproduits = detaiproduits;
		this.assoproduitunites = assoproduitunites;
		this.lots = lots;
	}

	public int getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(int idproduit) {
		this.idproduit = idproduit;
	}

	public Famille getFamille() {
		return this.famille;
	}

	public void setFamille(Famille famille) {
		this.famille = famille;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getEtat() {
		return this.etat;
	}

	public void setEtat(Boolean etat) {
		this.etat = etat;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Set getDetaiproduits() {
		return this.detaiproduits;
	}

	public void setDetaiproduits(Set detaiproduits) {
		this.detaiproduits = detaiproduits;
	}

	public Set getAssoproduitunites() {
		return this.assoproduitunites;
	}

	public void setAssoproduitunites(Set assoproduitunites) {
		this.assoproduitunites = assoproduitunites;
	}

	public Set getLots() {
		return this.lots;
	}

	public void setLots(Set lots) {
		this.lots = lots;
	}

}
