package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Promotion generated by hbm2java
 */
public class Promotion implements java.io.Serializable {

	private int idpromotion;
	private String titrepromotion;
	private Date datedebut;
	private Date datefin;
	private Double pourcentagereduction;
	private String codepromo;
	private String description;
	private Integer nombreutilisationsmax;
	private Integer nombreutilisationsactuel;
	private Set articles = new HashSet(0);

	public Promotion() {
	}

	public Promotion(int idpromotion) {
		this.idpromotion = idpromotion;
	}

	public Promotion(int idpromotion, String titrepromotion, Date datedebut, Date datefin, Double pourcentagereduction,
			String codepromo, String description, Integer nombreutilisationsmax, Integer nombreutilisationsactuel,
			Set articles) {
		this.idpromotion = idpromotion;
		this.titrepromotion = titrepromotion;
		this.datedebut = datedebut;
		this.datefin = datefin;
		this.pourcentagereduction = pourcentagereduction;
		this.codepromo = codepromo;
		this.description = description;
		this.nombreutilisationsmax = nombreutilisationsmax;
		this.nombreutilisationsactuel = nombreutilisationsactuel;
		this.articles = articles;
	}

	public int getIdpromotion() {
		return this.idpromotion;
	}

	public void setIdpromotion(int idpromotion) {
		this.idpromotion = idpromotion;
	}

	public String getTitrepromotion() {
		return this.titrepromotion;
	}

	public void setTitrepromotion(String titrepromotion) {
		this.titrepromotion = titrepromotion;
	}

	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}

	public Double getPourcentagereduction() {
		return this.pourcentagereduction;
	}

	public void setPourcentagereduction(Double pourcentagereduction) {
		this.pourcentagereduction = pourcentagereduction;
	}

	public String getCodepromo() {
		return this.codepromo;
	}

	public void setCodepromo(String codepromo) {
		this.codepromo = codepromo;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getNombreutilisationsmax() {
		return this.nombreutilisationsmax;
	}

	public void setNombreutilisationsmax(Integer nombreutilisationsmax) {
		this.nombreutilisationsmax = nombreutilisationsmax;
	}

	public Integer getNombreutilisationsactuel() {
		return this.nombreutilisationsactuel;
	}

	public void setNombreutilisationsactuel(Integer nombreutilisationsactuel) {
		this.nombreutilisationsactuel = nombreutilisationsactuel;
	}

	public Set getArticles() {
		return this.articles;
	}

	public void setArticles(Set articles) {
		this.articles = articles;
	}

}
