package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

/**
 * RoleId generated by hbm2java
 */
public class RoleId implements java.io.Serializable {

	private int idconnexion;
	private int idpermission;

	public RoleId() {
	}

	public RoleId(int idconnexion, int idpermission) {
		this.idconnexion = idconnexion;
		this.idpermission = idpermission;
	}

	public int getIdconnexion() {
		return this.idconnexion;
	}

	public void setIdconnexion(int idconnexion) {
		this.idconnexion = idconnexion;
	}

	public int getIdpermission() {
		return this.idpermission;
	}

	public void setIdpermission(int idpermission) {
		this.idpermission = idpermission;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleId))
			return false;
		RoleId castOther = (RoleId) other;

		return (this.getIdconnexion() == castOther.getIdconnexion())
				&& (this.getIdpermission() == castOther.getIdpermission());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdconnexion();
		result = 37 * result + this.getIdpermission();
		return result;
	}

}
