package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Societe generated by hbm2java
 */
public class Societe implements java.io.Serializable {

	private int idsociete;
	private String nomsociete;
	private String address;
	private String phone;
	private Set collaborateurs = new HashSet(0);

	public Societe() {
	}

	public Societe(int idsociete) {
		this.idsociete = idsociete;
	}

	public Societe(int idsociete, String nomsociete, String address, String phone, Set collaborateurs) {
		this.idsociete = idsociete;
		this.nomsociete = nomsociete;
		this.address = address;
		this.phone = phone;
		this.collaborateurs = collaborateurs;
	}

	public int getIdsociete() {
		return this.idsociete;
	}

	public void setIdsociete(int idsociete) {
		this.idsociete = idsociete;
	}

	public String getNomsociete() {
		return this.nomsociete;
	}

	public void setNomsociete(String nomsociete) {
		this.nomsociete = nomsociete;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getCollaborateurs() {
		return this.collaborateurs;
	}

	public void setCollaborateurs(Set collaborateurs) {
		this.collaborateurs = collaborateurs;
	}

}
