package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private int idstock;
	private String designation;
	private String qrcode;
	private Date datecreation;
	private Boolean etat;
	private Integer datemodification;
	private Set lots = new HashSet(0);

	public Stock() {
	}

	public Stock(int idstock) {
		this.idstock = idstock;
	}

	public Stock(int idstock, String designation, String qrcode, Date datecreation, Boolean etat,
			Integer datemodification, Set lots) {
		this.idstock = idstock;
		this.designation = designation;
		this.qrcode = qrcode;
		this.datecreation = datecreation;
		this.etat = etat;
		this.datemodification = datemodification;
		this.lots = lots;
	}

	public int getIdstock() {
		return this.idstock;
	}

	public void setIdstock(int idstock) {
		this.idstock = idstock;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Boolean getEtat() {
		return this.etat;
	}

	public void setEtat(Boolean etat) {
		this.etat = etat;
	}

	public Integer getDatemodification() {
		return this.datemodification;
	}

	public void setDatemodification(Integer datemodification) {
		this.datemodification = datemodification;
	}

	public Set getLots() {
		return this.lots;
	}

	public void setLots(Set lots) {
		this.lots = lots;
	}

}
