package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	private int idtransaction;
	private Categorietransaction categorietransaction;
	private Compte compte;
	private String type;
	private Byte montant;
	private String description;
	private String categorie;
	private Date date;
	private Boolean validee;
	private String source;
	private Set assoreporttransats = new HashSet(0);

	public Transaction() {
	}

	public Transaction(int idtransaction, Compte compte) {
		this.idtransaction = idtransaction;
		this.compte = compte;
	}

	public Transaction(int idtransaction, Categorietransaction categorietransaction, Compte compte, String type,
			Byte montant, String description, String categorie, Date date, Boolean validee, String source,
			Set assoreporttransats) {
		this.idtransaction = idtransaction;
		this.categorietransaction = categorietransaction;
		this.compte = compte;
		this.type = type;
		this.montant = montant;
		this.description = description;
		this.categorie = categorie;
		this.date = date;
		this.validee = validee;
		this.source = source;
		this.assoreporttransats = assoreporttransats;
	}

	public int getIdtransaction() {
		return this.idtransaction;
	}

	public void setIdtransaction(int idtransaction) {
		this.idtransaction = idtransaction;
	}

	public Categorietransaction getCategorietransaction() {
		return this.categorietransaction;
	}

	public void setCategorietransaction(Categorietransaction categorietransaction) {
		this.categorietransaction = categorietransaction;
	}

	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Boolean getValidee() {
		return this.validee;
	}

	public void setValidee(Boolean validee) {
		this.validee = validee;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Set getAssoreporttransats() {
		return this.assoreporttransats;
	}

	public void setAssoreporttransats(Set assoreporttransats) {
		this.assoreporttransats = assoreporttransats;
	}

}
