package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Typecontrat generated by hbm2java
 */
public class Typecontrat implements java.io.Serializable {

	private int idtypecontract;
	private String libelle;
	private String etat;
	private Date datecreation;
	private Set contrattravails = new HashSet(0);

	public Typecontrat() {
	}

	public Typecontrat(int idtypecontract) {
		this.idtypecontract = idtypecontract;
	}

	public Typecontrat(int idtypecontract, String libelle, String etat, Date datecreation, Set contrattravails) {
		this.idtypecontract = idtypecontract;
		this.libelle = libelle;
		this.etat = etat;
		this.datecreation = datecreation;
		this.contrattravails = contrattravails;
	}

	public int getIdtypecontract() {
		return this.idtypecontract;
	}

	public void setIdtypecontract(int idtypecontract) {
		this.idtypecontract = idtypecontract;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Set getContrattravails() {
		return this.contrattravails;
	}

	public void setContrattravails(Set contrattravails) {
		this.contrattravails = contrattravails;
	}

}
