package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Typevariete generated by hbm2java
 */
public class Typevariete implements java.io.Serializable {

	private int idtypevariete;
	private String label;
	private String typevaleur;
	private String etat;
	private Date datecreation;
	private Set varietes = new HashSet(0);

	public Typevariete() {
	}

	public Typevariete(int idtypevariete) {
		this.idtypevariete = idtypevariete;
	}

	public Typevariete(int idtypevariete, String label, String typevaleur, String etat, Date datecreation,
			Set varietes) {
		this.idtypevariete = idtypevariete;
		this.label = label;
		this.typevaleur = typevaleur;
		this.etat = etat;
		this.datecreation = datecreation;
		this.varietes = varietes;
	}

	public int getIdtypevariete() {
		return this.idtypevariete;
	}

	public void setIdtypevariete(int idtypevariete) {
		this.idtypevariete = idtypevariete;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getTypevaleur() {
		return this.typevaleur;
	}

	public void setTypevaleur(String typevaleur) {
		this.typevaleur = typevaleur;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Set getVarietes() {
		return this.varietes;
	}

	public void setVarietes(Set varietes) {
		this.varietes = varietes;
	}

}
