package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Unitemesure generated by hbm2java
 */
public class Unitemesure implements java.io.Serializable {

	private int idunite;
	private String libelle;
	private String symbole;
	private Set assoproduitunites = new HashSet(0);

	public Unitemesure() {
	}

	public Unitemesure(int idunite) {
		this.idunite = idunite;
	}

	public Unitemesure(int idunite, String libelle, String symbole, Set assoproduitunites) {
		this.idunite = idunite;
		this.libelle = libelle;
		this.symbole = symbole;
		this.assoproduitunites = assoproduitunites;
	}

	public int getIdunite() {
		return this.idunite;
	}

	public void setIdunite(int idunite) {
		this.idunite = idunite;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getSymbole() {
		return this.symbole;
	}

	public void setSymbole(String symbole) {
		this.symbole = symbole;
	}

	public Set getAssoproduitunites() {
		return this.assoproduitunites;
	}

	public void setAssoproduitunites(Set assoproduitunites) {
		this.assoproduitunites = assoproduitunites;
	}

}
