package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

/**
 * VarieteId generated by hbm2java
 */
public class VarieteId implements java.io.Serializable {

	private int idarticle;
	private int idtypevariete;
	private int idvariete;

	public VarieteId() {
	}

	public VarieteId(int idarticle, int idtypevariete, int idvariete) {
		this.idarticle = idarticle;
		this.idtypevariete = idtypevariete;
		this.idvariete = idvariete;
	}

	public int getIdarticle() {
		return this.idarticle;
	}

	public void setIdarticle(int idarticle) {
		this.idarticle = idarticle;
	}

	public int getIdtypevariete() {
		return this.idtypevariete;
	}

	public void setIdtypevariete(int idtypevariete) {
		this.idtypevariete = idtypevariete;
	}

	public int getIdvariete() {
		return this.idvariete;
	}

	public void setIdvariete(int idvariete) {
		this.idvariete = idvariete;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VarieteId))
			return false;
		VarieteId castOther = (VarieteId) other;

		return (this.getIdarticle() == castOther.getIdarticle())
				&& (this.getIdtypevariete() == castOther.getIdtypevariete())
				&& (this.getIdvariete() == castOther.getIdvariete());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdarticle();
		result = 37 * result + this.getIdtypevariete();
		result = 37 * result + this.getIdvariete();
		return result;
	}

}
