package models.classes;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vente generated by hbm2java
 */
public class Vente implements java.io.Serializable {

	private int idvente;
	private Assocomptecaisse assocomptecaisse;
	private Client client;
	private Integer reference;
	private Date datecommande;
	private Byte montanttotal;
	private String modepaiement;
	private String statut;
	private Date date;
	private Set livraisons = new HashSet(0);
	private Set detailventes = new HashSet(0);
	private Set factures = new HashSet(0);
	private Set retourproduits = new HashSet(0);

	public Vente() {
	}

	public Vente(int idvente, Assocomptecaisse assocomptecaisse, Client client) {
		this.idvente = idvente;
		this.assocomptecaisse = assocomptecaisse;
		this.client = client;
	}

	public Vente(int idvente, Assocomptecaisse assocomptecaisse, Client client, Integer reference, Date datecommande,
			Byte montanttotal, String modepaiement, String statut, Date date, Set livraisons, Set detailventes,
			Set factures, Set retourproduits) {
		this.idvente = idvente;
		this.assocomptecaisse = assocomptecaisse;
		this.client = client;
		this.reference = reference;
		this.datecommande = datecommande;
		this.montanttotal = montanttotal;
		this.modepaiement = modepaiement;
		this.statut = statut;
		this.date = date;
		this.livraisons = livraisons;
		this.detailventes = detailventes;
		this.factures = factures;
		this.retourproduits = retourproduits;
	}

	public int getIdvente() {
		return this.idvente;
	}

	public void setIdvente(int idvente) {
		this.idvente = idvente;
	}

	public Assocomptecaisse getAssocomptecaisse() {
		return this.assocomptecaisse;
	}

	public void setAssocomptecaisse(Assocomptecaisse assocomptecaisse) {
		this.assocomptecaisse = assocomptecaisse;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Integer getReference() {
		return this.reference;
	}

	public void setReference(Integer reference) {
		this.reference = reference;
	}

	public Date getDatecommande() {
		return this.datecommande;
	}

	public void setDatecommande(Date datecommande) {
		this.datecommande = datecommande;
	}

	public Byte getMontanttotal() {
		return this.montanttotal;
	}

	public void setMontanttotal(Byte montanttotal) {
		this.montanttotal = montanttotal;
	}

	public String getModepaiement() {
		return this.modepaiement;
	}

	public void setModepaiement(String modepaiement) {
		this.modepaiement = modepaiement;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set getLivraisons() {
		return this.livraisons;
	}

	public void setLivraisons(Set livraisons) {
		this.livraisons = livraisons;
	}

	public Set getDetailventes() {
		return this.detailventes;
	}

	public void setDetailventes(Set detailventes) {
		this.detailventes = detailventes;
	}

	public Set getFactures() {
		return this.factures;
	}

	public void setFactures(Set factures) {
		this.factures = factures;
	}

	public Set getRetourproduits() {
		return this.retourproduits;
	}

	public void setRetourproduits(Set retourproduits) {
		this.retourproduits = retourproduits;
	}

}
