package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

/**
 * AssocomptecaisseId generated by hbm2java
 */
public class AssocomptecaisseId implements java.io.Serializable {

	private int idconnexion;
	private int idcaisse;

	public AssocomptecaisseId() {
	}

	public AssocomptecaisseId(int idconnexion, int idcaisse) {
		this.idconnexion = idconnexion;
		this.idcaisse = idcaisse;
	}

	public int getIdconnexion() {
		return this.idconnexion;
	}

	public void setIdconnexion(int idconnexion) {
		this.idconnexion = idconnexion;
	}

	public int getIdcaisse() {
		return this.idcaisse;
	}

	public void setIdcaisse(int idcaisse) {
		this.idcaisse = idcaisse;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssocomptecaisseId))
			return false;
		AssocomptecaisseId castOther = (AssocomptecaisseId) other;

		return (this.getIdconnexion() == castOther.getIdconnexion()) && (this.getIdcaisse() == castOther.getIdcaisse());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdconnexion();
		result = 37 * result + this.getIdcaisse();
		return result;
	}

}
