package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

/**
 * AssoproduituniteId generated by hbm2java
 */
public class AssoproduituniteId implements java.io.Serializable {

	private int idunite;
	private int idproduit;

	public AssoproduituniteId() {
	}

	public AssoproduituniteId(int idunite, int idproduit) {
		this.idunite = idunite;
		this.idproduit = idproduit;
	}

	public int getIdunite() {
		return this.idunite;
	}

	public void setIdunite(int idunite) {
		this.idunite = idunite;
	}

	public int getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(int idproduit) {
		this.idproduit = idproduit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssoproduituniteId))
			return false;
		AssoproduituniteId castOther = (AssoproduituniteId) other;

		return (this.getIdunite() == castOther.getIdunite()) && (this.getIdproduit() == castOther.getIdproduit());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdunite();
		result = 37 * result + this.getIdproduit();
		return result;
	}

}
