package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Assoproduitunite generated by hbm2java
 */
public class Assoproduitunite implements java.io.Serializable {

	private AssoproduituniteId id;
	private Produit produit;
	private Unitemesure unitemesure;
	private Date date;

	public Assoproduitunite() {
	}

	public Assoproduitunite(AssoproduituniteId id, Produit produit, Unitemesure unitemesure) {
		this.id = id;
		this.produit = produit;
		this.unitemesure = unitemesure;
	}

	public Assoproduitunite(AssoproduituniteId id, Produit produit, Unitemesure unitemesure, Date date) {
		this.id = id;
		this.produit = produit;
		this.unitemesure = unitemesure;
		this.date = date;
	}

	public AssoproduituniteId getId() {
		return this.id;
	}

	public void setId(AssoproduituniteId id) {
		this.id = id;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Unitemesure getUnitemesure() {
		return this.unitemesure;
	}

	public void setUnitemesure(Unitemesure unitemesure) {
		this.unitemesure = unitemesure;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
