package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

/**
 * AssoreporttransatId generated by hbm2java
 */
public class AssoreporttransatId implements java.io.Serializable {

	private int idrapport;
	private int idtransaction;

	public AssoreporttransatId() {
	}

	public AssoreporttransatId(int idrapport, int idtransaction) {
		this.idrapport = idrapport;
		this.idtransaction = idtransaction;
	}

	public int getIdrapport() {
		return this.idrapport;
	}

	public void setIdrapport(int idrapport) {
		this.idrapport = idrapport;
	}

	public int getIdtransaction() {
		return this.idtransaction;
	}

	public void setIdtransaction(int idtransaction) {
		this.idtransaction = idtransaction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssoreporttransatId))
			return false;
		AssoreporttransatId castOther = (AssoreporttransatId) other;

		return (this.getIdrapport() == castOther.getIdrapport())
				&& (this.getIdtransaction() == castOther.getIdtransaction());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdrapport();
		result = 37 * result + this.getIdtransaction();
		return result;
	}

}
