package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Boutique generated by hbm2java
 */
public class Boutique implements java.io.Serializable {

	private int idboutique;
	private Compte compte;
	private String nomboutique;
	private String reference;
	private Date datecreation;
	private Set lots = new HashSet(0);
	private Set employers = new HashSet(0);

	public Boutique() {
	}

	public Boutique(int idboutique) {
		this.idboutique = idboutique;
	}

	public Boutique(int idboutique, Compte compte, String nomboutique, String reference, Date datecreation, Set lots,
			Set employers) {
		this.idboutique = idboutique;
		this.compte = compte;
		this.nomboutique = nomboutique;
		this.reference = reference;
		this.datecreation = datecreation;
		this.lots = lots;
		this.employers = employers;
	}

	public int getIdboutique() {
		return this.idboutique;
	}

	public void setIdboutique(int idboutique) {
		this.idboutique = idboutique;
	}

	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	public String getNomboutique() {
		return this.nomboutique;
	}

	public void setNomboutique(String nomboutique) {
		this.nomboutique = nomboutique;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Set getLots() {
		return this.lots;
	}

	public void setLots(Set lots) {
		this.lots = lots;
	}

	public Set getEmployers() {
		return this.employers;
	}

	public void setEmployers(Set employers) {
		this.employers = employers;
	}

}
