package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Collaborateur generated by hbm2java
 */
public class Collaborateur implements java.io.Serializable {

	private CollaborateurId id;
	private Personne personne;
	private Societe societe;
	private String label;
	private Date datecreation;
	private String description;
	private Set casquettes = new HashSet(0);
	private Set livraisons = new HashSet(0);

	public Collaborateur() {
	}

	public Collaborateur(CollaborateurId id, Personne personne, Societe societe) {
		this.id = id;
		this.personne = personne;
		this.societe = societe;
	}

	public Collaborateur(CollaborateurId id, Personne personne, Societe societe, String label, Date datecreation,
			String description, Set casquettes, Set livraisons) {
		this.id = id;
		this.personne = personne;
		this.societe = societe;
		this.label = label;
		this.datecreation = datecreation;
		this.description = description;
		this.casquettes = casquettes;
		this.livraisons = livraisons;
	}

	public CollaborateurId getId() {
		return this.id;
	}

	public void setId(CollaborateurId id) {
		this.id = id;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getCasquettes() {
		return this.casquettes;
	}

	public void setCasquettes(Set casquettes) {
		this.casquettes = casquettes;
	}

	public Set getLivraisons() {
		return this.livraisons;
	}

	public void setLivraisons(Set livraisons) {
		this.livraisons = livraisons;
	}

}
