package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Detaiproduit generated by hbm2java
 */
public class Detaiproduit implements java.io.Serializable {

	private int iddetailproduit;
	private Produit produit;
	private String label;
	private Byte etat;
	private Date datecreation;

	public Detaiproduit() {
	}

	public Detaiproduit(int iddetailproduit) {
		this.iddetailproduit = iddetailproduit;
	}

	public Detaiproduit(int iddetailproduit, Produit produit, String label, Byte etat, Date datecreation) {
		this.iddetailproduit = iddetailproduit;
		this.produit = produit;
		this.label = label;
		this.etat = etat;
		this.datecreation = datecreation;
	}

	public int getIddetailproduit() {
		return this.iddetailproduit;
	}

	public void setIddetailproduit(int iddetailproduit) {
		this.iddetailproduit = iddetailproduit;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Byte getEtat() {
		return this.etat;
	}

	public void setEtat(Byte etat) {
		this.etat = etat;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

}
