package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Employer generated by hbm2java
 */
public class Employer implements java.io.Serializable {

	private EmployerId id;
	private Boutique boutique;
	private Personne personne;
	private Poste poste;
	private String matricule;
	private Set penalites = new HashSet(0);
	private Set conges = new HashSet(0);
	private Set contrattravails = new HashSet(0);

	public Employer() {
	}

	public Employer(EmployerId id, Personne personne, Poste poste) {
		this.id = id;
		this.personne = personne;
		this.poste = poste;
	}

	public Employer(EmployerId id, Boutique boutique, Personne personne, Poste poste, String matricule, Set penalites,
			Set conges, Set contrattravails) {
		this.id = id;
		this.boutique = boutique;
		this.personne = personne;
		this.poste = poste;
		this.matricule = matricule;
		this.penalites = penalites;
		this.conges = conges;
		this.contrattravails = contrattravails;
	}

	public EmployerId getId() {
		return this.id;
	}

	public void setId(EmployerId id) {
		this.id = id;
	}

	public Boutique getBoutique() {
		return this.boutique;
	}

	public void setBoutique(Boutique boutique) {
		this.boutique = boutique;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public Poste getPoste() {
		return this.poste;
	}

	public void setPoste(Poste poste) {
		this.poste = poste;
	}

	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	public Set getPenalites() {
		return this.penalites;
	}

	public void setPenalites(Set penalites) {
		this.penalites = penalites;
	}

	public Set getConges() {
		return this.conges;
	}

	public void setConges(Set conges) {
		this.conges = conges;
	}

	public Set getContrattravails() {
		return this.contrattravails;
	}

	public void setContrattravails(Set contrattravails) {
		this.contrattravails = contrattravails;
	}

}
