package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facture generated by hbm2java
 */
public class Facture implements java.io.Serializable {

	private int idfacture;
	private Vente vente;
	private String reference;
	private Date datefacture;
	private Byte montant;
	private Set paiements = new HashSet(0);

	public Facture() {
	}

	public Facture(int idfacture, Vente vente) {
		this.idfacture = idfacture;
		this.vente = vente;
	}

	public Facture(int idfacture, Vente vente, String reference, Date datefacture, Byte montant, Set paiements) {
		this.idfacture = idfacture;
		this.vente = vente;
		this.reference = reference;
		this.datefacture = datefacture;
		this.montant = montant;
		this.paiements = paiements;
	}

	public int getIdfacture() {
		return this.idfacture;
	}

	public void setIdfacture(int idfacture) {
		this.idfacture = idfacture;
	}

	public Vente getVente() {
		return this.vente;
	}

	public void setVente(Vente vente) {
		this.vente = vente;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Date getDatefacture() {
		return this.datefacture;
	}

	public void setDatefacture(Date datefacture) {
		this.datefacture = datefacture;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

	public Set getPaiements() {
		return this.paiements;
	}

	public void setPaiements(Set paiements) {
		this.paiements = paiements;
	}

}
