package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Historique generated by hbm2java
 */
public class Historique implements java.io.Serializable {

	private int idhistorique;
	private Compte compte;
	private String action;
	private String description;
	private Date date;

	public Historique() {
	}

	public Historique(int idhistorique) {
		this.idhistorique = idhistorique;
	}

	public Historique(int idhistorique, Compte compte, String action, String description, Date date) {
		this.idhistorique = idhistorique;
		this.compte = compte;
		this.action = action;
		this.description = description;
		this.date = date;
	}

	public int getIdhistorique() {
		return this.idhistorique;
	}

	public void setIdhistorique(int idhistorique) {
		this.idhistorique = idhistorique;
	}

	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
