package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Livraison generated by hbm2java
 */
public class Livraison implements java.io.Serializable {

	private int idlivraison;
	private Article article;
	private Collaborateur collaborateur;
	private Vente vente;
	private String reference;
	private Boolean statut;
	private Date date;
	private String type;

	public Livraison() {
	}

	public Livraison(int idlivraison, Article article, Collaborateur collaborateur, Vente vente) {
		this.idlivraison = idlivraison;
		this.article = article;
		this.collaborateur = collaborateur;
		this.vente = vente;
	}

	public Livraison(int idlivraison, Article article, Collaborateur collaborateur, Vente vente, String reference,
			Boolean statut, Date date, String type) {
		this.idlivraison = idlivraison;
		this.article = article;
		this.collaborateur = collaborateur;
		this.vente = vente;
		this.reference = reference;
		this.statut = statut;
		this.date = date;
		this.type = type;
	}

	public int getIdlivraison() {
		return this.idlivraison;
	}

	public void setIdlivraison(int idlivraison) {
		this.idlivraison = idlivraison;
	}

	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	public Collaborateur getCollaborateur() {
		return this.collaborateur;
	}

	public void setCollaborateur(Collaborateur collaborateur) {
		this.collaborateur = collaborateur;
	}

	public Vente getVente() {
		return this.vente;
	}

	public void setVente(Vente vente) {
		this.vente = vente;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Boolean getStatut() {
		return this.statut;
	}

	public void setStatut(Boolean statut) {
		this.statut = statut;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
