package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Modepayement generated by hbm2java
 */
public class Modepayement implements java.io.Serializable {

	private int idmodepayement;
	private String typemode;
	private Set paiements = new HashSet(0);

	public Modepayement() {
	}

	public Modepayement(int idmodepayement) {
		this.idmodepayement = idmodepayement;
	}

	public Modepayement(int idmodepayement, String typemode, Set paiements) {
		this.idmodepayement = idmodepayement;
		this.typemode = typemode;
		this.paiements = paiements;
	}

	public int getIdmodepayement() {
		return this.idmodepayement;
	}

	public void setIdmodepayement(int idmodepayement) {
		this.idmodepayement = idmodepayement;
	}

	public String getTypemode() {
		return this.typemode;
	}

	public void setTypemode(String typemode) {
		this.typemode = typemode;
	}

	public Set getPaiements() {
		return this.paiements;
	}

	public void setPaiements(Set paiements) {
		this.paiements = paiements;
	}

}
