package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

/**
 * Motifretour generated by hbm2java
 */
public class Motifretour implements java.io.Serializable {

	private int idmotif;
	private Retourproduit retourproduit;
	private String libelle;

	public Motifretour() {
	}

	public Motifretour(int idmotif, Retourproduit retourproduit) {
		this.idmotif = idmotif;
		this.retourproduit = retourproduit;
	}

	public Motifretour(int idmotif, Retourproduit retourproduit, String libelle) {
		this.idmotif = idmotif;
		this.retourproduit = retourproduit;
		this.libelle = libelle;
	}

	public int getIdmotif() {
		return this.idmotif;
	}

	public void setIdmotif(int idmotif) {
		this.idmotif = idmotif;
	}

	public Retourproduit getRetourproduit() {
		return this.retourproduit;
	}

	public void setRetourproduit(Retourproduit retourproduit) {
		this.retourproduit = retourproduit;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
