package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Paiement generated by hbm2java
 */
public class Paiement implements java.io.Serializable {

	private int idpaiement;
	private Facture facture;
	private Modepayement modepayement;
	private Byte montantpaye;
	private Date datepaiement;
	private String statutpaiement;

	public Paiement() {
	}

	public Paiement(int idpaiement, Facture facture, Modepayement modepayement) {
		this.idpaiement = idpaiement;
		this.facture = facture;
		this.modepayement = modepayement;
	}

	public Paiement(int idpaiement, Facture facture, Modepayement modepayement, Byte montantpaye, Date datepaiement,
			String statutpaiement) {
		this.idpaiement = idpaiement;
		this.facture = facture;
		this.modepayement = modepayement;
		this.montantpaye = montantpaye;
		this.datepaiement = datepaiement;
		this.statutpaiement = statutpaiement;
	}

	public int getIdpaiement() {
		return this.idpaiement;
	}

	public void setIdpaiement(int idpaiement) {
		this.idpaiement = idpaiement;
	}

	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	public Modepayement getModepayement() {
		return this.modepayement;
	}

	public void setModepayement(Modepayement modepayement) {
		this.modepayement = modepayement;
	}

	public Byte getMontantpaye() {
		return this.montantpaye;
	}

	public void setMontantpaye(Byte montantpaye) {
		this.montantpaye = montantpaye;
	}

	public Date getDatepaiement() {
		return this.datepaiement;
	}

	public void setDatepaiement(Date datepaiement) {
		this.datepaiement = datepaiement;
	}

	public String getStatutpaiement() {
		return this.statutpaiement;
	}

	public void setStatutpaiement(String statutpaiement) {
		this.statutpaiement = statutpaiement;
	}

}
