package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Payementsalaire generated by hbm2java
 */
public class Payementsalaire implements java.io.Serializable {

	private int idpaye;
	private Byte montant;
	private Date dateeffectif;
	private String etat;
	private String periodicite;
	private String period;
	private Set contrattravails = new HashSet(0);

	public Payementsalaire() {
	}

	public Payementsalaire(int idpaye) {
		this.idpaye = idpaye;
	}

	public Payementsalaire(int idpaye, Byte montant, Date dateeffectif, String etat, String periodicite, String period,
			Set contrattravails) {
		this.idpaye = idpaye;
		this.montant = montant;
		this.dateeffectif = dateeffectif;
		this.etat = etat;
		this.periodicite = periodicite;
		this.period = period;
		this.contrattravails = contrattravails;
	}

	public int getIdpaye() {
		return this.idpaye;
	}

	public void setIdpaye(int idpaye) {
		this.idpaye = idpaye;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

	public Date getDateeffectif() {
		return this.dateeffectif;
	}

	public void setDateeffectif(Date dateeffectif) {
		this.dateeffectif = dateeffectif;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public String getPeriodicite() {
		return this.periodicite;
	}

	public void setPeriodicite(String periodicite) {
		this.periodicite = periodicite;
	}

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public Set getContrattravails() {
		return this.contrattravails;
	}

	public void setContrattravails(Set contrattravails) {
		this.contrattravails = contrattravails;
	}

}
