package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Penalite generated by hbm2java
 */
public class Penalite implements java.io.Serializable {

	private int idpenalite;
	private Employer employer;
	private Date datepenalite;
	private String motif;
	private String sanction;

	public Penalite() {
	}

	public Penalite(int idpenalite, Employer employer) {
		this.idpenalite = idpenalite;
		this.employer = employer;
	}

	public Penalite(int idpenalite, Employer employer, Date datepenalite, String motif, String sanction) {
		this.idpenalite = idpenalite;
		this.employer = employer;
		this.datepenalite = datepenalite;
		this.motif = motif;
		this.sanction = sanction;
	}

	public int getIdpenalite() {
		return this.idpenalite;
	}

	public void setIdpenalite(int idpenalite) {
		this.idpenalite = idpenalite;
	}

	public Employer getEmployer() {
		return this.employer;
	}

	public void setEmployer(Employer employer) {
		this.employer = employer;
	}

	public Date getDatepenalite() {
		return this.datepenalite;
	}

	public void setDatepenalite(Date datepenalite) {
		this.datepenalite = datepenalite;
	}

	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	public String getSanction() {
		return this.sanction;
	}

	public void setSanction(String sanction) {
		this.sanction = sanction;
	}

}
