package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rapportfinancier generated by hbm2java
 */
public class Rapportfinancier implements java.io.Serializable {

	private int idrapport;
	private Compte compte;
	private String periode;
	private Date datedebut;
	private Date datefin;
	private Byte totaleentries;
	private Byte totalesorties;
	private Byte solde;
	private Set assoreporttransats = new HashSet(0);

	public Rapportfinancier() {
	}

	public Rapportfinancier(int idrapport) {
		this.idrapport = idrapport;
	}

	public Rapportfinancier(int idrapport, Compte compte, String periode, Date datedebut, Date datefin,
			Byte totaleentries, Byte totalesorties, Byte solde, Set assoreporttransats) {
		this.idrapport = idrapport;
		this.compte = compte;
		this.periode = periode;
		this.datedebut = datedebut;
		this.datefin = datefin;
		this.totaleentries = totaleentries;
		this.totalesorties = totalesorties;
		this.solde = solde;
		this.assoreporttransats = assoreporttransats;
	}

	public int getIdrapport() {
		return this.idrapport;
	}

	public void setIdrapport(int idrapport) {
		this.idrapport = idrapport;
	}

	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	public String getPeriode() {
		return this.periode;
	}

	public void setPeriode(String periode) {
		this.periode = periode;
	}

	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}

	public Byte getTotaleentries() {
		return this.totaleentries;
	}

	public void setTotaleentries(Byte totaleentries) {
		this.totaleentries = totaleentries;
	}

	public Byte getTotalesorties() {
		return this.totalesorties;
	}

	public void setTotalesorties(Byte totalesorties) {
		this.totalesorties = totalesorties;
	}

	public Byte getSolde() {
		return this.solde;
	}

	public void setSolde(Byte solde) {
		this.solde = solde;
	}

	public Set getAssoreporttransats() {
		return this.assoreporttransats;
	}

	public void setAssoreporttransats(Set assoreporttransats) {
		this.assoreporttransats = assoreporttransats;
	}

}
