package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Retourproduit generated by hbm2java
 */
public class Retourproduit implements java.io.Serializable {

	private int idretoure;
	private Article article;
	private Vente vente;
	private Byte quantiteretournee;
	private Date dateretour;
	private String motif;
	private String statut;
	private String actionappliquee;
	private String type;
	private Set motifretours = new HashSet(0);

	public Retourproduit() {
	}

	public Retourproduit(int idretoure, Article article, Vente vente) {
		this.idretoure = idretoure;
		this.article = article;
		this.vente = vente;
	}

	public Retourproduit(int idretoure, Article article, Vente vente, Byte quantiteretournee, Date dateretour,
			String motif, String statut, String actionappliquee, String type, Set motifretours) {
		this.idretoure = idretoure;
		this.article = article;
		this.vente = vente;
		this.quantiteretournee = quantiteretournee;
		this.dateretour = dateretour;
		this.motif = motif;
		this.statut = statut;
		this.actionappliquee = actionappliquee;
		this.type = type;
		this.motifretours = motifretours;
	}

	public int getIdretoure() {
		return this.idretoure;
	}

	public void setIdretoure(int idretoure) {
		this.idretoure = idretoure;
	}

	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	public Vente getVente() {
		return this.vente;
	}

	public void setVente(Vente vente) {
		this.vente = vente;
	}

	public Byte getQuantiteretournee() {
		return this.quantiteretournee;
	}

	public void setQuantiteretournee(Byte quantiteretournee) {
		this.quantiteretournee = quantiteretournee;
	}

	public Date getDateretour() {
		return this.dateretour;
	}

	public void setDateretour(Date dateretour) {
		this.dateretour = dateretour;
	}

	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public String getActionappliquee() {
		return this.actionappliquee;
	}

	public void setActionappliquee(String actionappliquee) {
		this.actionappliquee = actionappliquee;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getMotifretours() {
		return this.motifretours;
	}

	public void setMotifretours(Set motifretours) {
		this.motifretours = motifretours;
	}

}
