package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private RoleId id;
	private Compte compte;
	private Permission permission;
	private String datecreation;
	private Boolean etat;

	public Role() {
	}

	public Role(RoleId id, Compte compte, Permission permission) {
		this.id = id;
		this.compte = compte;
		this.permission = permission;
	}

	public Role(RoleId id, Compte compte, Permission permission, String datecreation, Boolean etat) {
		this.id = id;
		this.compte = compte;
		this.permission = permission;
		this.datecreation = datecreation;
		this.etat = etat;
	}

	public RoleId getId() {
		return this.id;
	}

	public void setId(RoleId id) {
		this.id = id;
	}

	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	public Boolean getEtat() {
		return this.etat;
	}

	public void setEtat(Boolean etat) {
		this.etat = etat;
	}

}
