package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Salaire generated by hbm2java
 */
public class Salaire implements java.io.Serializable {

	private int idsalaire;
	private Varietesalaire varietesalaire;
	private Byte montant;
	private Date date;
	private Set contrattravails = new HashSet(0);

	public Salaire() {
	}

	public Salaire(int idsalaire, Varietesalaire varietesalaire) {
		this.idsalaire = idsalaire;
		this.varietesalaire = varietesalaire;
	}

	public Salaire(int idsalaire, Varietesalaire varietesalaire, Byte montant, Date date, Set contrattravails) {
		this.idsalaire = idsalaire;
		this.varietesalaire = varietesalaire;
		this.montant = montant;
		this.date = date;
		this.contrattravails = contrattravails;
	}

	public int getIdsalaire() {
		return this.idsalaire;
	}

	public void setIdsalaire(int idsalaire) {
		this.idsalaire = idsalaire;
	}

	public Varietesalaire getVarietesalaire() {
		return this.varietesalaire;
	}

	public void setVarietesalaire(Varietesalaire varietesalaire) {
		this.varietesalaire = varietesalaire;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set getContrattravails() {
		return this.contrattravails;
	}

	public void setContrattravails(Set contrattravails) {
		this.contrattravails = contrattravails;
	}

}
