package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Variete generated by hbm2java
 */
public class Variete implements java.io.Serializable {

	private VarieteId id;
	private Article article;
	private Typevariete typevariete;
	private String valeur;
	private Boolean etat;
	private Date datecreation;

	public Variete() {
	}

	public Variete(VarieteId id, Article article, Typevariete typevariete) {
		this.id = id;
		this.article = article;
		this.typevariete = typevariete;
	}

	public Variete(VarieteId id, Article article, Typevariete typevariete, String valeur, Boolean etat,
			Date datecreation) {
		this.id = id;
		this.article = article;
		this.typevariete = typevariete;
		this.valeur = valeur;
		this.etat = etat;
		this.datecreation = datecreation;
	}

	public VarieteId getId() {
		return this.id;
	}

	public void setId(VarieteId id) {
		this.id = id;
	}

	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	public Typevariete getTypevariete() {
		return this.typevariete;
	}

	public void setTypevariete(Typevariete typevariete) {
		this.typevariete = typevariete;
	}

	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	public Boolean getEtat() {
		return this.etat;
	}

	public void setEtat(Boolean etat) {
		this.etat = etat;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

}
