package models;
// Generated Jun 1, 2025, 7:59:38 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Varietesalaire generated by hbm2java
 */
public class Varietesalaire implements java.io.Serializable {

	private int idvarietesalaire;
	private String libellevariete;
	private Date datecreation;
	private Set salaires = new HashSet(0);

	public Varietesalaire() {
	}

	public Varietesalaire(int idvarietesalaire) {
		this.idvarietesalaire = idvarietesalaire;
	}

	public Varietesalaire(int idvarietesalaire, String libellevariete, Date datecreation, Set salaires) {
		this.idvarietesalaire = idvarietesalaire;
		this.libellevariete = libellevariete;
		this.datecreation = datecreation;
		this.salaires = salaires;
	}

	public int getIdvarietesalaire() {
		return this.idvarietesalaire;
	}

	public void setIdvarietesalaire(int idvarietesalaire) {
		this.idvarietesalaire = idvarietesalaire;
	}

	public String getLibellevariete() {
		return this.libellevariete;
	}

	public void setLibellevariete(String libellevariete) {
		this.libellevariete = libellevariete;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Set getSalaires() {
		return this.salaires;
	}

	public void setSalaires(Set salaires) {
		this.salaires = salaires;
	}

}
